modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/desht/ModularRouters/issues"
displayURL="https://minecraft.curseforge.com/projects/modular-routers"
credits=""
authors="${mod_authors}"
license="MIT"

[[mods]] #mandatory
modId="modularrouters" #mandatory
version="${mod_version}" #mandatory
displayName="Modular Routers"
updateJSONURL="https://raw.githubusercontent.com/desht/ModularRouters/MC1.20.4-master/release_info.json" #optional
description="${mod_description}"

[[dependencies.modularrouters]]
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.modularrouters]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
